// Code Generated by Sidekick is for learning and experimentation purposes only.
pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
              git branch: 'main', url: 'https://github.com/rchak-git/MyJenkinsFirstProject.git'
            }
        }
        stage('Build') {
            steps {
                bat 'mvn clean install'
            }
        }
        stage('Test') {
            steps {
                bat 'mvn test'
            }
        }
    }
}
