package Utils;

// Code Generated by Sidekick is for learning and experimentation purposes only.
import com.aventstack.extentreports.ExtentReports;
import com.aventstack.extentreports.reporter.ExtentSparkReporter;

import java.io.File;
import java.io.IOException;

public class ExtentReportSetup {

    private static ExtentReports extent;
    private static final String REPORT_FILE_PATH = "TestReports/ExtentReport.html"; // Keep it simple

    public static ExtentReports setupExtentReport() {
        if (extent == null) {
            String filePath = REPORT_FILE_PATH;
            File reportFile = new File(filePath);
            File reportDir = reportFile.getParentFile();

            // Check if parent directory is null (shouldn't be in this case)
            if (reportDir == null) {
                System.err.println("Parent directory is null!  This is unexpected.");
            } else if (!reportDir.exists()) {
                System.err.println("Directory doesn't exist.  Attempting to create: " + reportDir.getAbsolutePath());
                reportDir.mkdirs(); // Create the directory if it doesn't exist
            }

            ExtentSparkReporter spark = new ExtentSparkReporter(filePath); // Report file name
            extent = new ExtentReports();
            extent.attachReporter(spark);
        }
        return extent;
    }

    public static void main(String[] args) throws IOException {
        System.out.println("Working Directory = " + System.getProperty("user.dir")); // Confirm working directory
        ExtentReports extentReports = setupExtentReport();
        extentReports.createTest("My First Test").pass("This test passed");
        extentReports.flush(); // Required to write the report to the file
        System.out.println("Report generated at: " + new File(REPORT_FILE_PATH).getAbsolutePath());
    }
}
