package Utils;

// Code Generated by Sidekick is for learning and experimentation purposes only.
public class PathUtil {

    /**
     * Returns the absolute path to the project root directory.
     */
    public static String getProjectRootPath() {
        return System.getProperty("user.dir");
    }

    /**
     * Returns the absolute path to a resource in src/test/resources.
     */
    public static String getTestResourcePath() {
        return getProjectRootPath() + "/src/test/Java/resources/" + "TestData.xlsx";
    }
}
