package Utils;

// Code Generated by Sidekick is for learning and experimentation purposes only.

import java.lang.annotation.*;

@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.METHOD)
public @interface TestDescription {
    String value();
}
