package tests.tests;

// Code Generated by Sidekick is for learning and experimentation purposes only.

import Resources.ExcelDataProviders;
import Utils.ExcelDataUtil;
import automation.pages.LoginPage;
import org.testng.Assert;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;
import tests.base.BaseTest;

import java.util.Map;

public class LoginTest extends BaseTest {
    private LoginPage loginPage;

    @BeforeMethod
    public void navigateToLoginPage() {
        driver.get("https://the-internet.herokuapp.com/login");
        loginPage = new LoginPage(driver);
    }

    @Test
    public void testValidLogin() {
         Map<String,String>  testdata = ExcelDataUtil.getDataById("Sheet1","Login-01");
        String userName = testdata.get("Username");
        loginPage.enterUsername(userName);
        loginPage.enterPassword(testdata.get("Password"));
        loginPage.clickLogin();
        String message = loginPage.getFlashMessage();
        Assert.assertTrue(message.contains("You logged into a secure area!"));
    }


    @Test(dataProvider = "loginData",dataProviderClass = ExcelDataProviders.class )
    public void testValidLoginUsingDataProvider(Map<String, String> testdata) {
        navigateToLoginPage();
        String userName = testdata.get("Username");
        loginPage.enterUsername(userName);
        loginPage.enterPassword(testdata.get("Password"));
        loginPage.clickLogin();
       // String message = loginPage.getFlashMessage();
       // Assert.assertTrue(message.contains("You logged into a secure area!"));
    }
}
